# Generated by Django 5.0.6 on 2024-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('state_abbrev', models.CharField(max_length=255)),
                ('state_region', models.CharField(max_length=255)),
                ('state_division', models.CharField(max_length=255)),
            ],
        ),
    ]
