# Generated by Django 5.0.6 on 2024-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statesproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
